# The name of your workflow. 
# GitHub displays the names of your workflows on your repository's actions page. 
##name: Publish deafrica-tools to PyPI
name: Publish deafrica-tools to Test PyPI
# Specifies the triggers for this workflow. 
on:
  # Triggers the workflow to run  when 
  # 1) a push occurs on the main branch that includes changes to any file in the Tools/ directory,
  # 2) when a release has been published or 
  # 3) by clicking the 'Run workflow' button on the Actions tab.
  push:
    branches:
      #- main
      - test-publishing-using-poetry
    paths:
      - 'Tools/**'
  release:
    types: [published]
  workflow_dispatch:

# Groups together all the jobs that run in the workflow. 
# A workflow run is made up of one or more jobs. 
# Jobs run in parallel by default.
jobs:
  # Job unique identifier.
  build-n-publish:
    # Name for the job, which is displayed on GitHub.
    #name: Build and publish deafrica-tools to PyPI
    name: Build and publish deafrica-tools to Test PyPI
    # Specifies the runner environment the job will run in. 
    # Configure the job to run on the latest version of an Ubuntu Linux runner.
    runs-on: ubuntu-latest
    # Groups together all the steps that run in the job. 
    # A job contains a sequence of tasks called steps. 
    # Each item nested under this section is a separate action or shell script. 
    steps:
      # The uses keyword specifies that this step will run v3 of the actions/checkout action. 
      # This is an action that checks out your repository onto the runner (downloads your repository into the CI runner), 
      # allowing you to run scripts or other actions against your code (such as build and test tools). 
      # You should use the checkout action any time your workflow will run against the repository's code.
      - name: Checkout the digitalearthafrica/deafrica-sandbox-notebooks repository
        uses: actions/checkout@v3
      # Build package distributions from source and publish to Test PyPI
      - name: Build and Publish distribution 📦 to Test PyPI
        # You may pin to the exact commit or the version of the action.
        uses: JRubics/poetry-publish@v1.17
        with:
          # The version of python to install
          python_version: "3.10.6"
          # The version of poetry to install
          poetry_version: "==1.5.0" # (PIP version specifier syntax)
          # Required API token to authenticate when uploading package to PyPI
          pypi_token: ${{secrets.TEST_PYPI_API_TOKEN}}
          # Name of a repository where the package will be uploaded.
          repository_name: "testpypi"
          # The URL where the package will be uploaded.
          repository_url: "https://test.pypi.org/legacy/"
          # An optional subdirectory path if poetry package 
          # doesn't reside in the main workflow directory
          package_directory: "../../Tools"