# This workflow publishes the deafrica-tools to TestPyPi.

# The name of your workflow. GitHub displays the names of your workflows on your repository's actions page. 
name: Publish deafrica-tools to TestPyPI
# Defines which events can cause the workflow to run. 
on:
  # Triggers the workflow to run  1) when a push that includes a change to any file in the Tools/ directory and/or a change to this workflow file is made to the publish-deafrica-tools branch or 2) when a release has been published or 3) by clicking the 'Run workflow' button on the Actions tab.
  push:
    branches:
      - publish-deafrica-tools
    paths:
      - 'Tools/**'
      - '.github/workflows/see_tags.yml'
  release:
    types: [published]
  workflow_dispatch:

# A workflow run is made up of one or more jobs, which run in parallel by default.
# This workflow contains a single job called "Publish".
jobs:
  # Job unique identifier.
  build-n-publish:
    # Name for the job, which is displayed on GitHub.
    name: Build and publish deafrica-tools to TestPyPI
    # Specifies the runner environment the 'publish' job will run in.
    runs-on: ubuntu-latest
    # A job contains a sequence of tasks called steps.
    steps:
      # The uses keyword specifies that this step will run v2 of the actions/checkout action. This is an action that checks out your repository onto the runner, allowing you to run scripts or other actions against your code (such as build and test tools). You should use the checkout action any time your workflow will run against the repository's code. $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v3
        with:  
          repository: vikineema/deafrica-sandbox-notebooks

      - name: Get history and tags for SCM versioning to work
        run: |
          git fetch --prune --unshallow --tags
          git fetch --depth=1 upstream +refs/tags/*:refs/tags/*
          git describe --tags
          git describe --tags $(git rev-list --tags --max-count=1)
